import interpolate from '../../contours/interpolation/interpolate';
import type { InterpolationViewportData } from '../../../types/InterpolationTypes';
import deleteRelatedAnnotations from './deleteRelatedAnnotations';

/**
 * updatedRelatedContours - Update the same roi contour id contours on modifying
 * one of them .
 *
 * @param eventData - Object.
 * @returns null
 */
export default function updateRelatedAnnotations(
  viewportData: InterpolationViewportData,
  isLabelUpdate = true
) {
  const { annotation } = viewportData;

  if (isLabelUpdate) {
    console.log('isLabelUpdate');
    delete annotation.interpolationUID;
    deleteRelatedAnnotations(viewportData);
  } else {
    console.log(
      'Starting update related interpolate',
      annotation.autoGenerated,
      annotation.metadata?.referencedSliceIndex
    );
    interpolate(viewportData);
  }
}
