packages:
  - packages/adapters
  - packages/core
  - packages/dicomImageLoader
  - packages/docs
  - packages/nifti-volume-loader
  - packages/polymorphic-segmentation
  - packages/tools
  - packages/ai
  - packages/labelmap-interpolation
  - addOns/externals/*
  - addOns/local/*
onlyBuiltDependencies:
  - canvas
  - core-js
  - core-js-pure
  - protobufjs
  - puppeteer
ignoredBuiltDependencies:
  - unrs-resolver
