import InterpolationManager from '../../segmentation/InterpolationManager/InterpolationManager.js';
import type { AcceptInterpolationSelector } from '../../../types/InterpolationTypes.js';
import type AnnotationGroupSelector from '../../../types/AnnotationGroupSelector.js';

/**
 * Accepts interpolated annotations, marking them as autoGenerated false.
 *
 * @param annotationGroupSelector - viewport or FOR to select annotations on
 * @param selector - nested selection criteria
 */
export default function acceptAutogeneratedInterpolations(
  annotationGroupSelector: AnnotationGroupSelector,
  selector: AcceptInterpolationSelector
) {
  InterpolationManager.acceptAutoGenerated(annotationGroupSelector, selector);
}
