import { Types, utilities } from '@cornerstonejs/core';
import { Annotation } from '../types';
import { addAnnotation } from '../stateManagement';

function hydration(
  viewport: Types.IViewport,
  toolName: string,
  worldPoints: Types.Point3[],
  options?: {
    FrameOfReferenceUID?: string;
  }
): Annotation {
  const viewReference = viewport.getViewReference();
  const annotation = {
    annotationUID: utilities.uuidv4(),
    data: {
      handles: {
        points: worldPoints,
      },
    },
    handles: {},
    highlighted: false,
    autoGenerated: false,
    invalidated: false,
    isLocked: false,
    isVisible: true,
    metadata: {
      toolName,
      ...viewReference,
      ...options,
    },
  };
  addAnnotation(annotation, viewport.element);
  return annotation;
}

export { hydration };
