name: Playwright Tests
on:
  pull_request:
    branches: [main, master, beta]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: 20
            mode: legacy
            run_args: "all --project=chromium"
            collect_coverage: true
          - node-version: 20
            mode: compatibility
            run_args: "--compat --project=chromium"
            collect_coverage: false
          - node-version: 20
            mode: next
            run_args: "next --project=chromium"
            collect_coverage: false
    name: Playwright (${{ matrix.mode }})
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.23
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Install Playwright browsers
        run: bun x playwright install chromium
      - name: Run Playwright tests
        env:
          COVERAGE: ${{ matrix.collect_coverage && 'true' || '' }}
        run: |
          export NODE_OPTIONS="--max_old_space_size=10192"
          if [ "${{ matrix.collect_coverage }}" = "true" ]; then
            bun x nyc --reporter=html ./scripts/run-playright.sh ${{ matrix.run_args }}
          else
            ./scripts/run-playright.sh ${{ matrix.run_args }}
          fi
      - name: create the coverage report
        if: ${{ matrix.collect_coverage }}
        run: |
          bun nyc report --reporter=lcov --reporter=text
      - name: Upload the coverage report to GitHub Actions Artifacts
        if: ${{ !cancelled() && matrix.collect_coverage }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-pr
          path: coverage
          retention-days: 7
      - name: Upload Playwright reports
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.mode }}
          path: reports/*playwright
          retention-days: 7
